CREATE TABLE IF NOT EXISTS PRODUCTS(
PRODUCT_ID INTEGER,
PRODUCT_NAME TEXT,
SUPPLIER_ID INTEGER,
CATEGORY_ID TEXT,
UNIT INTEGER,
PRICE REAL
);
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)VALUES
(1,"PASTA",101,"A",5,239),
(2,"FRYING PAN",100,"B",8,904),
(3,"PEN STAND",189,"D",6,289),
(5,"CHOPSTICKS",191,"C",3,739),
(4,"CAKE",201,"E",2,2039);

SELECT COUNT(PRODUCT_ID)AS product_count FROM PRODUCTS;
SELECT AVG(PRICE)AS average_price FROM PRODUCTS;
SELECT sum(PRICE)AS total_price FROM PRODUCTS;
