CREATE TABLE IF NOT EXISTS EMPLOYEE(
EMPLOYEE_ID INTEGER,
EMPLOYEE_NAME TEXT,
SECTION_ID TEXT,
SALARY INTEGER
);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,SUPPLIER_ID,SECTION_ID,UNIT,PRICE)VALUES
(1,"MIN HO","A",200039),
(2,"YURI HAN","B",90004),
(3,"DAE KIM","D",20089),
(5,"JULIANA MENH","C",78000),
(4,"ESTHER SHIM","E",100000);

SELECT COUNT(EMPLOYEE_ID)AS employee_count FROM EMPLOYEE;
SELECT AVG(PRICE)AS average_price FROM EMPLOYEE;
SELECT sum(PRICE)AS total_price FROM EMPLOYEE;
