CREATE TABLE IF NOT EXISTS NOBEL_WIN(
YEAR INTEGER,
WINNER TEXT,
COUNTRY TEXT,
SUBJECT TEXT
);
INSERT INTO NOBEL_WIN(YEAR,WINNER,COUNTRY,SUBJECT)VALUES
(1993,"MIN HO","KOREA","CHEMISTRY"),
(1973,"SHELDON","USA","SCIENCE"),
(1997,"MINIHA","ARGENTINA","MATHS"),
(1899,"MELLISA","UK","BIOLOGY");

SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE "C%";
