CREATE TABLE supplier(
SNO TEXT PRIMARY KEY,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT
);
INSERT INTO supplier (SNO,SNAME,STATUS,CITY) VALUES
("L1","JUSTIN",1,"GERMANY"),
("L2","KATHERINE",2,"PORTLAND"),
("L3","PETER",3,"AMERICA");
SELECT * FROM supplier;
